version: '3.8'

services:

  spotify-client:
    build:
      context: ./src/Spotify.Client/UI/
      dockerfile: ./Dockerfile
    container_name: 'spotify-client'
    ports:
      - 7057:80

  spotify-server:
    build:
      context: ./src/Spotify.Backend/src/DB/
      dockerfile: ./Dockerfile
    container_name: 'spotify-server'
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=SpotifyServer;Username=postgres;Password=admin
    ports:
      - 7030:80

  spotify-admindashboard-client:
    build:
      context: ./src/Spotify.AdminDashboard/admin-ui/
      dockerfile: ./Dockerfile
    container_name: 'spotify-admindashboard-client'
    ports:
      - 8081:8081

  spotify-admindashboard-server:
    build:
      context: ./src/Spotify.AdminDashboard/admin-api/
      dockerfile: ./Dockerfile
    container_name: 'spotify-admindashboard-server'
    ports:
      - 8080:8080

  server:
    build:
      context: ./src/Spotify.Support/server
      dockerfile: ./Chat.Api/Dockerfile
    container_name: 'server'
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=Chat;Username=postgres;Password=admin

      - RabbitMQ__Hostname=rabbitmq
      - RabbitMQ__Port=5672

      - AWS__ServiceURL=http://s3:8000
      - AWS__AccessKey=access
      - AWS__AccessSecret=secret
      - AWS__Buckets__Temp=files-temp
      - AWS__Buckets__Persistent=files-persistent

      - Redis__Port=6379
      - Redis__Password=password
      - Redis__Host=cache

      - MongoDB__Database=meta
      - MongoDB__Host=metastorage
      - MongoDB__Port=27017
      - MongoDB__User=mongo
      - MongoDB__Password=admin
    ports:
      - "5225:80"
    depends_on:
      - s3
      - metastorage
      - db

  client:
    build:
      context: ./src/Spotify.Support/client
      dockerfile: ./Dockerfile
    environment:
      - HOST=0.0.0.0
    ports:
      - "5173:5173"

  rabbitmq:
      image: rabbitmq:3-management-alpine
      ports:
        - 5672:5672
        - 15672:15672
      restart: always

  mqconsumer:
    build:
      context: ./src/Spotify.Support/server
      dockerfile: ./Chat.BackgroundService/Dockerfile
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=Chat;Username=postgres;Password=admin
      
      - RabbitMQ__Hostname=rabbitmq
      - RabbitMQ__Port=5672

      - Redis__Port=6379
      - Redis__Password=password
      - Redis__Host=cache

      - MongoDB__Database=meta
      - MongoDB__Host=metastorage
      - MongoDB__Port=27017
      - MongoDB__User=mongo
      - MongoDB__Password=admin
    ports:
      - "8001:80"
    restart: always
    depends_on:
      - rabbitmq

  db:
    image: postgres
    container_name: 'db'
    ports:
      - "7000:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "admin"
      POSTGRES_DB: "Chat"
    restart: always

  metastorage:
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=admin
    restart: always

  s3:
    image: zenko/cloudserver
    container_name: "s3"
    ports:
      - 8000:8000
    environment:
      - SCALITY_ACCESS_KEY_ID=access
      - SCALITY_SECRET_ACCESS_KEY=secret
      - S3DATA=multiple
      - S3BACKEND=mem
      - ENDPOINT=s3
    restart: always

  cache:
    image: 'redis:latest'
    ports: 
      - 6379:6379
    environment:
      - REDIS_PASSWORD=password
