version: '3.8'

services:
  chat-server:
    build: 
      context: ./server
      dockerfile: ./Chat.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8000:80"
  chat-client:
    build: 
      context: ./client
      dockerfile: ./Dockerfile
    environment:
      - HOST=0.0.0.0
    ports:
      - "5173:5173"
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "admin"
      POSTGRES_DB: "Chat"
  rmq:
    image: rabbitmq:latest
    ports:
      - "15672:15672"
      - "5672:5672"