version: '3.8'

# networks:
#   app-tier:
#     driver: bridge

services:

  chat-server:
    build:
      context: ./server
      dockerfile: ./Chat.Api/Dockerfile
    container_name: 'server'
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8000:80"
    depends_on:
      - rabbitmq

  chat-client:
    build:
      context: ./client
      dockerfile: ./Dockerfile
    environment:
      - HOST=0.0.0.0
    ports:
      - "5173:5173"

  chat-consumer:
    build:
      context: ./server
      dockerfile: ./Chat.BackgroundService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8001:80"
    depends_on:
      - rabbitmq

  db:
    image: postgres
    container_name: 'db'
    ports:
      - "7000:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "admin"
      POSTGRES_DB: "Chat"

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672